// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWnwQnBLo95gvgqVLdx0SguuSr1mbpOZc',
    appId: '1:1000042618201:web:37afeedcba722b1d834048',
    messagingSenderId: '1000042618201',
    projectId: 'tot-task-app',
    authDomain: 'tot-task-app.firebaseapp.com',
    storageBucket: 'tot-task-app.firebasestorage.app',
    measurementId: 'G-ZSSVJYCNC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF3X47I-WPwDaB8qumcsmiL6iVCIPxQso',
    appId: '1:1000042618201:android:3d6f2d239eb71ac0834048',
    messagingSenderId: '1000042618201',
    projectId: 'tot-task-app',
    storageBucket: 'tot-task-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwn--hW3Cddx0LAl5QVfgC6nAJIzITkXQ',
    appId: '1:1000042618201:ios:7d1eac99e89426e4834048',
    messagingSenderId: '1000042618201',
    projectId: 'tot-task-app',
    storageBucket: 'tot-task-app.firebasestorage.app',
    iosBundleId: 'com.example.totApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwn--hW3Cddx0LAl5QVfgC6nAJIzITkXQ',
    appId: '1:1000042618201:ios:7d1eac99e89426e4834048',
    messagingSenderId: '1000042618201',
    projectId: 'tot-task-app',
    storageBucket: 'tot-task-app.firebasestorage.app',
    iosBundleId: 'com.example.totApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWnwQnBLo95gvgqVLdx0SguuSr1mbpOZc',
    appId: '1:1000042618201:web:bdbfd6adb4e52492834048',
    messagingSenderId: '1000042618201',
    projectId: 'tot-task-app',
    authDomain: 'tot-task-app.firebaseapp.com',
    storageBucket: 'tot-task-app.firebasestorage.app',
    measurementId: 'G-MH0B713B11',
  );
}
